### ISSUE TITLE
folder pages in components

### ISSUE THREAD

**Issue by cezarneaga** [citizennext/hartaservicii#1]
de ce ai pus folderul asta in components? 
paginile le-as pastra in src/pages

**Comment by st3phan-cs** [comment]
@cezarneaga @secosan 

1. ’src/pages' = routes declarations
2. ‘src/components/pages’ = structure of pages
3. ‘src/components/pages/<Page>/*’ = sections of page

1. Aici sa declaram doar ceea ce inseamna rute
2. AIci cream structura paginii pe Layout in functie de coloane
3. Aici impartim continutul pagii in functie de Layout si pe sectiuni

Acest tip de arhitectura ajuta foarte mult la o consistenta a paginilor, codului, declaratiilor, …, si e mult mai usor de manipulat

**Comment by secosan** [comment]
Eu aici sunt deacord cu Cezar, dar best practises zice precum solutia lui Stefan.

Nu inteleg de ce sa declari undeva doar o ruta ca apoi sa declari o structura in alta parte, mai studiez putin si discutam maine in call.

**Comment by cezarneaga** [comment]
mi se pare ciudat, dar prefer sa fim rapizi in dezvoltare decat sa discutam foldere.
