### ISSUE TITLE
Dynamic Statistic Map

### ISSUE THREAD

**Issue by st3phan-cs** [citizennext/hartaservicii#53]

**Comment by cezarneaga** [comment]
@st3phan-cs  aici as vrea sa mai adaugam hover tooltip care sa arate numarul si numele judetului

**Comment by st3phan-cs** [comment]
> @st3phan-cs aici as vrea sa mai adaugam hover tooltip care sa arate numarul si numele judetului

@cezarneaga este facut si este in develop

**Comment by cezarneaga** [comment]
by tooltip ma refeream la asta: https://wwayne.github.io/react-tooltip/
